# Site settings
title:              the CV template
author:             your name
email:              you email
description:        desc
keywords:           [kw1, kw2, kw3]
url:                http://mageluer.coding.me/CV

# Jekyll
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true

########################################################################
# Begin CV Edit
########################################################################

# Personal Info
info:
  avatar:          images/image.jpg
  name:            Zilu Tang
  description:     I'm a drinker
  address:         Wuhan University Wuhan, China
  email:           tangziluwh@163.com
  tel:             +86-15207175816
  web:             www.maybemad.github.io

# Intro
intro:
  display:         false
  content:         

# Education
education:
  - period:        Sep 2014 - present
    institute:     Wuhan University
    school:        College of Chemistry and Molecular Sciences
  

# Performance
performance:
  display:         false
  gpa:             3.99
  rank:            1/1000

# TOEFL & GRE
stdtest:
  display:         true
  toefl:           81
  gre:             310

# Experience
experience:
  - period:        Oct 2014 - present
    institute:     Green Catalysis Institution (College of Chemistry and Molecular Sciences, Wuhan University)
    desc:          Prof. Aiwen Lei
    project:
      -            Synthesis and properties analysis of Lithium Ion Batteries and SrMgF$_4$ 
      -            Study the formation mechanism of hexagonal ferrite Sr$_3$Co$_2$Fe$_{24}$O$_{41}$ pure phase
      -            Investigating the optimization of SrMgF$_4$ 
  

# Skills
skill:
  display:        true 
  software:       [Word, Excel, PowerPoint, Origin, Chem3D, Chemdraw ]
  

# Publications
publication:
  - time:          2017-04-18
    title:         Zhang, G.H.; <b>Yi, H.</b>; Zhang, G.T.; Deng, Y.; Bai, R.P.; Zhang, H.; Miller, J.T.; Kropf, A.J.; Bunel, E.E.; Lei, A.W., <i> J Am Chem Soc</i> <b>2014</b>, 136, 924-926.
  - time:          2017-03-20
    title:         G.-Q. Shao, F.-F. Ma, J.-W. Mao, S.-H. Fan, A.-L. Zhang, <u>G.-Z. Xie</u>, C. Zhu, J.-N. Gu, J.-L. Yan, Crystal Structure of triplite LiFeSO$_4$F, CSD-432778, Inorganic Crystal Structure Database, FIZ Karlsruhe-Leibniz Inst. for Inform. Infrastr., Germany, 2017.3.20
  - time:          submitted
    title:         F.-F. Ma, J.-W. Mao, G.-Q. Shao, S.-H. Fan, C. Zhu, A.-L. Zhang, <u>G.-Z. Xie</u>, J.-N. Gu, and J.-L. Yan, Structure of triplite LiFeSO$_4$F powder synthesized through an ambient two-step solid-state route, Powder Diffraction
  - time:          submitted
    title:         S.-H. Fan, G.-Q. Shao, J.-W. Mao, F.-F. Ma, C. Zhu, A.-L. Zhang, <u>G.-Z. Xie</u>, J.-L. Yan and J.-N. Gu, Crystal structure and electrochemical properties of LiFe$_{1-x}$V$_x$PO$_4$F$_{1-δ}$O$_δ$ cathode materials for lithium-ion batteries, Electrochimica Acta

# Patents
patent:
  display:         false
  list:
    - time:        2017-08-31
      title:       邵刚勤，柳金华，毛家威，<u>谢贵震</u>，范书豪，马霏霏，张安乐，“一种高温稳定的氟磷酸铁锂型锂离子电池材料及其制备方法”，中国发明专利201610226791.9，2016.4.14申请，公开号CN 105914344A，公开日2016.08.31
    - time:        2017-05-03
      title:       邵刚勤，张安乐，<u>谢贵震</u>，朱璨，顾佳妮，晏佳礼，马霏霏，范书豪，毛家威，一种高纯度X型六角锶钴铁氧体材料的制备方法，中国发明专利201710304747.X，2017.5.3申请
    - time:        2017-05-03
      title:       邵刚勤，马霏霏，毛家威，范书豪，朱璨，张安乐，<u>谢贵震</u>，顾佳妮，晏佳礼，一种高温稳定的相变型氟硫酸铁锂电池材料的制备方法及电极片与锂离子电池的使用方法，中国发明专利201710305189.9，2017.5.3申请
    - time:        2017-05-03
      title:       邵刚勤，范书豪，毛家威，马霏霏，朱璨，张安乐，<u>谢贵震</u>，晏佳礼，顾佳妮，一种氟氧磷酸盐锂离子电池材料的制备方法及正极片与锂离子电池，中国发明专利201710304314.4，2017.5.3申请

# Activities
activity:
  display:        true
  hobby:          [table tennis, Dota2]
  experience:
    -             Travelling footprints left over 10 provinces, over 100 railway tickets
    -             co-managing a YHA with my friend in Lhasa, Tibet
  

